dataset:
  frames_per_sample: 1
  batch_size: 1
  num_workers: 1
  binary_task: true
  train_data_dir: "./datasets/lasot"
  val_data_dir: "./datasets/lasot"
  max_frames: 4

train:
  learning_rate: 0.00001
  weight_decay: 0.0001
  max_epochs: 10
  last_frame_loss_weight: 1.2
  precision: "float32" #float 32
  #strategy: "ddp"
  log_dir: "samari-tiny"
  accelerator: "gpu"
  devices: "-1"
  loss_type: "smooth_l1"
  kf_loss_weight: 1.0
  mamba_loss_weight: 0.3
  run_name: "SamariTinyLocal"

model:
  encoder:
    input_channels: 3  # Just RGB
    channels:
      - 16
      - 32
      - 64
    kernels:
      - [3, 3, 3]
      - [3, 3, 3]
      - [3, 3, 3]
    strides:
      - [1, 1, 1]
      - [1, 1, 1]
      - [1, 1, 1]  # Keep T dimension
    paddings:
      - [1, 1, 1]
      - [1, 1, 1]
      - [1, 1, 1]
    pool_kernels:
      - [1, 2, 2]
      - [1, 2, 2]
      - [1, 2, 2]  # Pool H, W
    pool_paddings:
      - [0, 0, 0]
      - [0, 0, 0]
      - [0, 0, 0]

  mamba:
    d_model: 128  # Dimension for Mamba layer
    d_state: 16
    d_conv: 4
    expand: 2

  bbox_embedding_dim: 64